# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 657c5fb8eff58d41e3bbf2a446c9b1667c9542ed303f823468137d024361932a6926bf78e096d3de9908c0733a3fa2a47b422d19ce86ea615db7d42fa8221844

test:
  secret_key_base: 16a496d7ddadf2f482f788f027910364b10ebe3e9ed107dfd1620972ca4ceda0cf3464bdfce5a1193acdf810d317db072be69fa3a6c69356669a324c4e50d553

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
